### ISSUE TITLE
Work with server

### ISSUE THREAD

**Issue by MariaJsn** [drawRect/Instagram_Stories#100]
How can I request server to get story before swipe to next story?

When story moves automatically to another one I can request to server than show story.
But when user swipe the screen for another story how can I request to the server?

**Comment by boominadhaprakash** [comment]
Hi @MariaJsn 

To implement this, you should know about the methods involved for this functionality. I will explain you about four methods which are responsible for story or snap movement.

1. **Method:** -> didCompleteProgress()

- You can find this method in IGStoryPreviewCell. This method is responsible for automatic snap movement. If one snap progressor completes, then this method will call for loading the next snap.

2. **Method:** -> didCompletePreview()

- You can find this method in IGStoryPreviewController. This method is responsible for story movement. Suppose first story having 3 snaps. Once all the 3 snaps are completed, then this method will trigger to load the next story.

3. **Method:** -> willMoveToPreviousOrNextSnap()

- You can find this method in IGStoryPreviewCell. This method is responsible for manual snap or story movement. Suppose user is tapping forward direction means, this method will trigger. When user taps, still that story has snaps means, it will move to that snap. Otherwise, this method will call didCompletePreview() method to load the next story.

4. **Method:** -> moveToPreviousStory()

- You can find this method in IGStoryPreviewController. This method is responsible for load the previous story when user taps backward.

Additionally, when user swipes the story, two scrollview delegate methods are implemented in IGStoryPreviewController. These methods will trigger when user swipes the story manually.
`func scrollViewWillBeginDragging(_ scrollView: UIScrollView)`
`func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool)`

Let me know, if you are not satisfied with my answer.

**Comment by boominadhaprakash** [comment]
@MariaJsn Hope we resolved your query and we are closing this issue.
