### ISSUE TITLE
The user is navigated back and forth based on where the user taps on a story.

### ISSUE THREAD

**Issue by sourish** [drawRect/Instagram_Stories#119]
https://user-images.githubusercontent.com/1575118/103912861-d1319d80-512d-11eb-8a29-9ea808fdcfe5.mov

**Describe the bug**
The user is navigated back and forth based on where the user taps on a story causing the user to go back and forth while the user switches between stories of different accounts while navigating quickly.

**To Reproduce**
1. Turn off the cubic Animation 
1. Launch the app.
2. Tap on any story.
3. Now quickly go forward or backward by tapping on the screen while viewing stories.
4. Observe when the user is switching between stories of accounts.

**Expected behavior**
The user should be navigated back and forth based on where the user taps on screen instead of the story itself.
                                           OR
The number of taps registered per second should be altered so that the user is unable to tap while in transition

**Comment by sourish** [comment]
@ranmyfriend / @boominadhaprakash : Could you please look into the issue. I have only stopped the cubic animator.

**Comment by boominadhaprakash** [comment]
Hi @sourish 

The code we wrote to support for Instagram Stories with cubic animation only. We are not supporting/implemented without cubic animation.

If you want without cubic animation, you can write your own logic like once animation starts you can make scrollView.isUserInteractionEnabled = false and once animation done, you can enable it or you can try some other library which are available on GitHub for without cubic animation.

To check this issue and restructure our code, will take some days. Because we both are busy in our own projects work.

**Comment by sourish** [comment]
Hi @boominadhaprakash ,

Thank U for the quick response.
Thank u for the suggestion, I will try the way u said & I did not get anything better than yours. 
If you can suggest any, I will check that project and may be it might help me.

I totally understand that.
