### ISSUE TITLE
Story controller closes second time

### ISSUE THREAD

**Issue by punitsilversky** [drawRect/Instagram_Stories#121]
Hi @boominadhaprakash 

I found one issue, that first time story view controller works fine. But, Second time it closes the controller without completing story

So, Please see this Zip File I've attached video in zip..

Please Look into this...

Thanks!
Punit

[Screen Recording 2021-01-13 at 3.08.35 PM.mov.zip](https://github.com/drawRect/Instagram_Stories/files/5807759/Screen.Recording.2021-01-13.at.3.08.35.PM.mov.zip)
..

**Comment by boominadhaprakash** [comment]
HI @punitsilversky 

Is that issue happening on our default master branch code?

**Comment by punitsilversky** [comment]
Hi @boominadhaprakash

In your default master branch code is working fine.

But I'm using your code in my app it generates above issue.

I'm trying to know why this issue comes

If you know something about this Please let me know or give some hint about that

Thanks!

**Comment by boominadhaprakash** [comment]
@punitsilversky 

Are you handling the data with already user viewed or not? If you are doing like that means, you have to check that logic only.

If you want to check the issue, comment all the implementation and enable the functionality one by one. So that you can easily find, which functionality making this issue.

**Comment by punitsilversky** [comment]
Thanks @boominadhaprakash

I will check and try to solve
