### ISSUE TITLE
How do I implement this into my app?

### ISSUE THREAD

**Issue by derens99** [drawRect/Instagram_Stories#37]

**Comment by ranmyfriend** [comment]
Hi @derens99  I recommend you to go through our JSON Structure
https://github.com/drawRect/Instagram_Stories/blob/master/InstagramStories/stories.json
Actually, we did not use any backend service here. We simply created on backup json in bundle file and loading all the Image Assets using the respective snaps and users. In our understanding, we defined the response if it comes in the manner it would handy from FrontEnd.

And in Front End side there are Two Screens (i)Home View Controller (ii)StoryPreviewController. The Flow is here. Whenever the user looking for a snap by tap gesture or automatic move around, Then we are creating new ImageView and adding at runtime. Then Starting the Image Request in the meanwhile we are showing the Image Loader. Once the Snaps become the last the trigger will go to load the next story. So, Basically the Story is Parent and Snap is Child. 1 story can have multiple Snaps. It applies on Forward and Backward.

We have replicated in the form of POC Level. We are trying our level best in future to do in Dependency level. I appreciate you to take a look at the code base and go through. And talk to your Backend Team. if we are designing like this JSON, what are the loopholes we can figure out? then you split the functionality from your end . Go step by step and implement tiny features first. Instead of focusing everything at once. 

Revert me if you have doubts or feedback about our code base. Feel free to spread the word about what we are doing here on your Network circle. 

**Known Issues: Fast Tapping will not give expected results.**

Thanks,
Ranjith
